spring:
  application:
    name: fire-tracker-service
  profiles:
    default: prod
server:
  port: 7777
logging:
  file:
    name: logs/fire-tracker-service.log
springdoc:
  api-docs:
    enabled: true
    path: /api/docs

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${HOST:localhost}:${PORT:5433}/postgres?user=postgres&password=postgres&currentSchema=fire_tracker_service_prod
    class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      group-id: default

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  prometheus:
    metrics:
      export:
        enabled: true

app:
  version: V1.0_BETA
  auth:
    secret: aWl0dV9zdWNrcw==
    expiration-millis: 900000
    issuer: IITU
  constant:
    risk-rate: 1
  services:
    nasa:
      url: https://firms.modaps.eosdis.nasa.gov/api
    open-weather:
      url: https://api.openweathermap.org/data/2.5
      token: 4490a59ec10f5a89677cf9381637e57e
      mocked: true
  topics:
    notify-consumers: fire-tracker-service-notify-consumers
