spring:
  application:
    name: fire-tracker-service
  profiles:
    default: prod
server:
  port: 8888
logging:
  file:
    name: logs/fire-tracker-service.log

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${HOST:localhost}:${PORT:5433}/postgres?user=postgres&password=postgres&currentSchema=fire_tracker_service_prod
    class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  prometheus:
    metrics:
      export:
        enabled: true

app:
  services:
    nasa:
      url: https://firms.modaps.eosdis.nasa.gov/api
      map-key: 046e1bd6f1fbd2f214a6bb39b6e41a50
    open-weather:
      url: https://api.openweathermap.org/data/2.5
      token: 4490a59ec10f5a89677cf9381637e57e
